development: &postgres
  adapter: postgis
  database: postgis-ft-dev
  host: localhost
  port: 5432
  pool: 25
  timeout: 5000

test:
  <<: *postgres
  database: postgis-ft-test

production:
  <<: *postgres
  database: postgis-ft-prod