development: &postgres
  adapter:   postgis
  database:  postgis-ft-dev
  host:      localhost
  user:      rails_user
  password:  rails_user
  port:      5432
  pool:      25
  timeout:   5000
  schema_search_path: public

test:
  <<: *postgres
  database: postgis-ft-test

production:
  <<: *postgres
  database: postgis-ft-prod